version: '3'

services: 
    tkai:
        container_name: tkai_services
        build: .
        tty: true
        ports: 
            - "8000:8000"
        networks: 
            - ktai
        depends_on: 
            - db
        links: 
            - db
        environment: 
            - db_name=postgres
            - db_pass=postgres
            - db_user=postgres
            - db_host=db
            - db_port=5432
            - token_password=thisIsTheJwtPassword
            - port=8000
    
    db:
        container_name: db
        image: postgres:latest
        restart: always
        ports: 
            - "5432:5432"
        networks: 
            - ktai
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

networks:
    ktai:

